{{- if .Values.customInitScript }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault.fullname" . }}-custom-init
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
data:
  custom-init.sh: |
{{- .Values.customInitScript | nindent 4 }}
{{- end}}

---

{{- if .Values.postStartScript }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault.fullname" . }}-post-start
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
data:
  post-start.sh: |
{{- .Values.postStartScript | nindent 4 }}
{{- end}}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault.fullname" . }}-configuration
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
data:
  {{- if .Values.server.standalone.enabled }}
  gcp.hcl: |
    seal "gcpckms" {
      project     = {{ .Values.server.standalone.googleProject | quote }}
      region      = {{ .Values.server.standalone.googleRegion | quote }}
      key_ring    = {{ .Values.server.standalone.gcpckmsSealKeyRing | quote }}
      crypto_key  = {{ .Values.server.standalone.gcpckmsSealCryptoKey | quote }}
    }
  {{- end }}
  {{- range $key, $value := .Values.server.extraConfigs }}
  {{ $key | quote }}: |
    {{- $key | indent 4 }}
  {{- end }}
