{{- if .Values.postStartScript }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault.fullname" . }}-post-start
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
data:
  post-start.sh: |
{{- .Values.postStartScript | nindent 4 }}
{{- end}}
