apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault.fullname" . }}-configuration
  labels:
    {{- include "vault.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  custom-init.sh: |
{{- .Values.customInitScript | nindent 4 }}
