{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "vault.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "vault.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
      - podSelector:
          matchLabels:
            {{ include "vault.fullname" . }}-client: "true"
{{- end }}
