{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "vault.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "vault.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{ include "vault.fullname" . }}-client: "true"
        {{- if .Values.ingress.enabled }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress
        # use a lable explicitly set by xdev in case we are in kubernetes < 1.21
        - namespaceSelector:
            matchLabels:
              name: ingress
        {{- end }}
{{- end }}
