apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "vault.labels" . | nindent 4 }}
  name: {{ include "vault.fullname" . }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
