{{- if or (not .Values.server.dev.existingSecret) (.Values.server.standalone.enabled) (.Values.server.initSecrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault.fullname" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if not .Values.server.dev.existingSecret }}
  VAULT_ROOT_TOKEN: {{ include "vault.devRootToken" . | b64enc | quote }}
  {{- end }}
  {{- if .Values.server.standalone.enabled }}
  VAULT_INIT_TOKEN: {{ .Values.server.standalone.initToken | b64enc | quote }}
  VAULT_INIT_PATH: {{ .Values.server.standalone.initPath | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.server.initSecrets }}
  {{ $key | quote }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
