apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault.fullname" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  vault-app-token: {{ include "vault.appToken" . | b64enc | quote }}