apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault.fullname" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  VAULT_ROOT_TOKEN: {{ include "vault.devRootToken" . | b64enc | quote }}
  {{- range $key, $value := .Values.server.initSecrets }}
  {{ $key | quote }}: {{ $value | b64enc | quote }}
  {{- end }}
