apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8200
      protocol: TCP
      name: http
      targetPort: http
  clusterIP: None
  selector:
    {{- include "vault.selectorLabels" . | nindent 4 }}
