{{- $fullName := include "vault.fullname" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vault.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  serviceName: {{ include "vault.fullname" . }}-headless
  selector:
    matchLabels:
      {{- include "vault.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vault.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vault.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or (not .Values.server.dev.existingSecret) (.Values.server.standalone.enabled) (.Values.server.initSecrets) }}
          envFrom:
            - secretRef:
                name: {{ include "vault.fullname" . }}
          {{- end }}
          env:
            - name: VAULT_DEBUG
              value: {{ .Values.server.debug | quote }}
            {{- if .Values.server.dev.existingSecret }}
            - name: VAULT_ROOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.server.dev.existingSecret . | quote }}
                  key: "root-token"
            {{- end }}
            {{- range $key, $value := .Values.server.initSecrets }}
            - name: {{ $key | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName | quote }}
                  key: {{ $key | quote }}
            {{- end }}
            {{- range $key, $value := .Values.extraEnvVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8200
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /vault/file
            - name: configuration
              mountPath: /extra/config
            {{- if .Values.customInitScript }}
            - name: custom-init-volume
              mountPath: /init
            {{- end }}
            {{- if .Values.postStartScript }}
            - name: post-start-volume
              mountPath: /post-start
            {{- end }}
          livenessProbe:
            httpGet:
              path: /v1/sys/health?sealedcode=200&uninitcode=200&standbyok=true
              port: http
          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true
              port: http
          {{- if .Values.postStartScript }}
          lifecycle:
            postStart:
              exec:
                command: ["sh", "/post-start/post-start.sh"]
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: configuration
          configMap:
            name: {{ include "vault.fullname" . }}-configuration
      {{- if .Values.customInitScript }}
        - name: custom-init-volume
          configMap:
            name: {{ include "vault.fullname" . }}-custom-init
      {{- end }}
      {{- if .Values.postStartScript }}
        - name: post-start-volume
          configMap:
            name: {{ include "vault.fullname" . }}-post-start
      {{- end }}
  {{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ tpl .Values.persistence.existingClaim $ }}
  {{- else if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
        {{- if .Values.persistence.annotations }}
        annotations: {{- toYaml .Values.persistence.annotations | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        {{- if .Values.persistence.dataSource }}
        dataSource: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.dataSource "context" $) | nindent 10 }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{- if .Values.persistence.selector }}
        selector: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.selector "context" $) | nindent 10 }}
        {{- end }}
        storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
