imageCredentials:
  registry: registry.gitlab.com
  username: maximevanmeerbeck
  password: EiYysZYicx7n4tbkWYua
  email: mvanmeerbeck@heblockchainxdev.com

server:
  debug: true

  dev:
    enabled: true
    devRootToken: "myroot"

  standalone:
    enabled: false